### ISSUE TITLE
reducing shapes

### ISSUE THREAD

**Issue by tcurdt** [tdewolff/canvas#16]
I am creating a PDF but the amount of shapes makes it really heavy to render.

So my idea was to render it into an image (`WriteImage`) first and then draw that image into the context for the PDF. Unfortunately it seems like `DrawImage` does not respect the transparency of the PNG.

Is there something I am missing? Or a better way than having all shapes in the PDF as is?

**Comment by tdewolff** [comment]
What happens is that `WriteImage` adds a white background. This should now be fixed, could you report back if it works for you?

**Comment by tcurdt** [comment]
Wow - that was fast :) Thanks!
This did solve the white background/transparency problem.

But something still does not look quite right.
Unfortunately github has upload problems so I added example images here:

vector:
https://i.paste.pics/d2f5eeb12f2e47d52bed79586d40ed40.png

pixel:
https://i.paste.pics/3fe17e7c7d5c9717bea28d2c5857d762.png

**Comment by tdewolff** [comment]
Can you check whether the colors that have transparency, are alpha pre-multiplied? For example, if you want to have 50% transparency, you should set the color as follows:

```
	col := canvas.Brown
	col.R /= 2
	col.G /= 2
	col.B /= 2
	col.A /= 2
```

and _not_ just the `A` channel. Let me know if this fixes it for you, I'm thinking of reporting an error when setting malformed colors, but a panic sound too much and a returned error is cumbersome to check for users...not sure how to proceed. Let me know if you have ideas.

**Comment by tcurdt** [comment]
Yes, the colors have transparencies. That's how the shapes get darker when being stacked.
But I did no pre-multiply them. That's the first I ever heard about such a thing. 🤔
Why is that a requirement?

**Comment by tdewolff** [comment]
That's how `color.RGBA` is implemented ;-), see https://golang.org/pkg/image/color/#RGBA

**Comment by tcurdt** [comment]
First time I used it :) Weird.
But now it works. Thanks for the help!
