### ISSUE TITLE
Empty new lines ignored

### ISSUE THREAD

**Issue by bcvery1** [tdewolff/canvas#191]
Empty new lines are ignored. Here is the code to reproduce (adapted from `examples` directory):
```go
package main

import (
	"github.com/tdewolff/canvas"
	"github.com/tdewolff/canvas/renderers"
)

var fontFamily *canvas.FontFamily

func main() {
	fontFamily = canvas.NewFontFamily("times")
	if err := fontFamily.LoadLocalFont("NimbusRoman-Regular", canvas.FontRegular); err != nil {
		panic(err)
	}

	c := canvas.New(200, 230)
	ctx := canvas.NewContext(c)
	ctx.SetFillColor(canvas.White)
	ctx.DrawPath(0, 0, canvas.Rectangle(c.W, c.H))
	draw(ctx)
	if err := renderers.Write("out.png", c, canvas.DPMM(5.0)); err != nil {
		panic(err)
	}
}

var y = 205.0

func drawText(c *canvas.Context, x float64, text *canvas.Text) {
	h := text.Bounds().H
	c.DrawText(x, y, text)
	y -= h + 10.0
}

func draw(c *canvas.Context) {
	c.SetFillColor(canvas.Black)
	textFace := fontFamily.Face(12.0, canvas.Black, canvas.FontRegular, canvas.FontNormal)

	drawText(c, 30.0, canvas.NewTextBox(textFace, "line 1\n\n\n\n\nline2", 140.0, 0.0, canvas.Justify, canvas.Top, 5.0, 0.0))
}
```

Here is the output, which is identical to having a single `\n` in the text:
![out](https://user-images.githubusercontent.com/5214789/202145514-8e63674c-a068-4f79-8185-e20cba9424f3.png)

**Comment by tdewolff** [comment]
Thanks Ben, should be fixed now!

**Comment by bcvery1** [comment]
Thanks for being so responsive! Unfortunately the issue with the above code is still present. I've pulled the latest commit.
From `go.mod`:
```
...
	github.com/tdewolff/canvas v0.0.0-20221116142110-6850588a236e
...
```

From `go.sum`:
```
...
github.com/tdewolff/canvas v0.0.0-20221116142110-6850588a236e h1:JIxnLOATpgYpcP8GKUibYy+7vEBePmKibxB+shYE2sU=
github.com/tdewolff/canvas v0.0.0-20221116142110-6850588a236e/go.mod h1:Sn30WhdB99OdqJcGRsRXLNOzSJs+AVycXVbG+M82ivY=
...
```

The `main.go` remains unchanged, so does the output image

**Comment by tdewolff** [comment]
That is weird, it works find here:
![out](https://user-images.githubusercontent.com/5563166/202234336-2bebdc20-384f-4ff2-b8c4-91da3310a011.png)

Are you sure you're at the latest version?

**Comment by bcvery1** [comment]
If it is a local issue, apologies for the confusion; I'll check now and report back

**Comment by bcvery1** [comment]
The problem was with my environment - this issue is resolved. Thanks again!
