### ISSUE TITLE
SVG renderer generates misaligned text

### ISSUE THREAD

**Issue by orzel7** [tdewolff/canvas#214]
Consider example:
```go:
package main

import (
	"fmt"
	"image/color"
	"os"

	"github.com/tdewolff/canvas"
	"github.com/tdewolff/canvas/renderers/svg"
)

func main() {
	f, err := os.Create("out.svg")
	if err != nil {
		panic(err)
	}
	defer f.Close()

	c := svg.New(f, 200, 200, nil)
	defer c.Close()

	ctx := canvas.NewContext(c)

	font, err := canvas.LoadFontFile("/usr/share/fonts/truetype/msttcorefonts/Tahoma Regular font.ttf", canvas.FontRegular)
	if err != nil {
		fmt.Println("Error:", err)
		return
	}

	face := font.Face(13, canvas.Black)

	s := "Here is\n a paragraph that requires word wrap X Y по рюззке тожэ"
	txt1 := canvas.NewTextBox(face, s, 36, 0, canvas.Right, canvas.Bottom, 0, 0)
	txt2 := canvas.NewTextBox(face, s, 36, 0, canvas.Left, canvas.Top, 0, 0)
	txt3 := canvas.NewTextBox(face, s, 36, 0, canvas.Middle, canvas.Top, 0, 0.5)

	ctx.SetCoordView(canvas.Identity)
	ctx.DrawText(100, 0, txt1)
	ctx.DrawText(0, 200, txt2)
	ctx.DrawText(50, 100, txt3)
	ctx.Rotate(-90)
	ctx.DrawText(100, 190, txt2)
	ctx.Rotate(90)

	ctx.SetStrokeColor(color.RGBA{0xff, 0, 0, 0xff})
	ctx.SetFillColor(color.RGBA{})
	ctx.SetStrokeWidth(1)
	bb := txt1.Bounds()
	bb.X -= 1
	bb.Y -= 1
	bb.W += 2
	bb.H += 2
	ctx.DrawPath(100, 0, bb.ToPath())
}
```

This code generates SVG file(see attachment). As you can notice, a line "a paragraph that" is slightly shifted to the left with some negative offset, compared to other lines.
![out](https://user-images.githubusercontent.com/82122403/229745637-37404c76-74b8-4bd2-a47d-32657454441d.svg)

**Comment by tdewolff** [comment]
Thanks for the bug report. I've now fixed the issue, please let me know how it goes!

Be aware that `Here is\n a paragraph` has a space after the literal newline, which forces there to be a space at the beginning of the line. You probably want to remove that space.

**Comment by orzel7** [comment]
Thank you for quick response.
After this change text still misaligned: lines after "a paragraph that". When text right-aligned, "a paragraph text" shifted slightly right. With space added after \n text still should be aligned properly. With extra space:
![out](https://user-images.githubusercontent.com/82122403/230222248-35a91343-d4d2-45b5-9215-4fe84d32c119.svg)
With extra space removed:
![out](https://user-images.githubusercontent.com/82122403/230222514-d57505af-1157-4293-bf94-2d578a6d5286.svg)

**Comment by tdewolff** [comment]
Yes, I figured out the same thing! I've pushed out a commit, does that fix it all?

**Comment by orzel7** [comment]
Hello, something has changed, but issues still exists.
1. Notice "thatrequires" lacks of space
2. Left alignment is still broken, see all lines behind "Here is"

Good news, right alignment works fine.
![out](https://user-images.githubusercontent.com/82122403/230295253-91d59026-30e5-4c88-b8e3-3620b5f85748.svg)

**Comment by tdewolff** [comment]
You're right, SVG and PDF targets were still broken. Should be good now!

**Comment by orzel7** [comment]
Thank you, looks great now.
